### ISSUE TITLE
Add support for Custom CSS

### ISSUE THREAD

**Issue by Jorengarenar** [Athou/commafeed#1024]
In version 2.6 there was very useful option to define our own CSS rules, but I don't see it anymore.
I really hope it will make a comeback, as there are a few (subjective) tweaks I'd love to apply to the UI.

**Comment by Athou** [comment]
Would a browser extension like [stylish](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en) be an acceptable replacement?

When I added the "Custom CSS" field, these kind of addons didn't exist and I feel like they do the job better than I could.

**Comment by Jorengarenar** [comment]
I'm actually a big fan of UserStyles and am already substituting the functionality with them.
That being said, they aren't ideal solution:

* aren't ubiquitous (I made the switch to CommaFeed because I wanted to have my RSS reader anywhere, be it my PC, laptop, workstation or smartphone).
* there is no good (in my opinion) mechanism at the moment for synchronizing the styles between devices/browsers.
* my instance isn't parked on any domain to match the style against.

If that's helpful I wouldn't mind 'Custom CSS' being on the admin side only, when configuring the server.
In fact, I'd probably be very happy with that. Simple CSS injection into generated DOM.

P.S. Don't use Stylish - it's reported spyware; [Stylus](https://github.com/openstyles/stylus) is better anyway

**Comment by Athou** [comment]
Thank you for the detailed explanation of the need for this feature.
I think I'll add it back but maybe not for the 3.0 release.

I aim for the 3.0 version to be a drop-in replacement for 2.6 with no database and no API changes. For this to be added back, I would need to clear the custom CSS field for everybody because it will not be compatible with the new UI and may cause issues. I don't think people would be happy with their custom css disappearing as they may not have a backup, so I plan to move the existing value in another field called "Legacy custom CSS" or something so people can retrieve their css rules.
