### ISSUE TITLE
"Unable to refresh feed"

### ISSUE THREAD

**Issue by Jorengarenar** [Athou/commafeed#1034]
It's probably related to my machine being suspended, but the feeds (all of them at once) sometimes don't refresh right away and in details page I have:

><sub>Last refresh</sub>
>_[value bigger than 10]_ minutes ago
><sub>Last refresh message</sub>
>Unable to refresh feed _[feed URL]_ : _[message]_
><sub>Next refresh</sub>
>in an _[an hour or two]_

Last time _[message]_ was just the domain of the website, now it was "Network is unreachable".

I have refresh rate set for 10 minutes, logs looks the same as usual.
The problem remains even after restarting the server. After some time (less than hour, but still more than 10 minutes) it does start working again as normal.

**Comment by Athou** [comment]
I'm not sure what is happening, although I never installed CommaFeed on a serverthat was suspended.

Did you enable the headyLoad flag in the configuration by any chance?

**Comment by Jorengarenar** [comment]
`heavyLoad` is false

**Comment by Athou** [comment]
I think I found the issue, when an error occurs more than 3 times when fetching a feed, the next fetch happens after an hour instead of refresh interval defined in the config. It's useful for instances with thousands of users but it's not really needed for personnal instances.

I commited a change to enable this behavior only for instances with the `heavyLoad` flag enabled. Can you confirm it fixes your problem?

**Comment by Jorengarenar** [comment]
Great :)
Now we will need just to wait a day or two to see if this solved the issue

**Comment by Jorengarenar** [comment]
Seems to be working :)
