### ISSUE TITLE
Follow system/browser dark/light mode

### ISSUE THREAD

**Issue by antivirtel** [Athou/commafeed#1083]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Is there a way to get Commafeed and the extension to check what mode the OS/Browser is in currently, and follow that? Usually called follow system.

**Describe alternatives you've considered**
Set it manually.

**Additional context**
https://github.com/Athou/commafeed-browser-extension/issues/1

**Comment by Athou** [comment]
[There is a way](https://mantine.dev/guides/dark-theme/#detect-user-preferred-color-scheme), but I'm wondering what happens when you click on the "Switch to light/dark theme" button in the menu. Since that value is stored in the localStorage, it's restored the next you visit the app. How would you go back to the "system preferred" setting?

**Comment by antivirtel** [comment]
There are usually 3 options in the settings. Dark/light & follow system. I'd also store it remotely, not just in the local storage.

**Comment by Athou** [comment]
Done! Still saved in the local storage for the moment though.

![image](https://github.com/Athou/commafeed/assets/1256795/07369c78-6771-441e-9175-267377a8cfc3)
