### ISSUE TITLE
Add setting to suppress the “Mark all entries as read” confirmation popup

### ISSUE THREAD

**Issue by emericv** [Athou/commafeed#1110]
When I click on “Mark all entries as read”, is there a way to suppress this confirmation step?

Thanks,
Emeric

**Comment by Athou** [comment]
Not at the moment, although the "shift+a" keyboard shortcut marks all entries as read, but does not ask for confirmation.

I could add a user setting to enable/disable the confirmation (it will remove the possibility to mark entries older than x days though).
I don't plan to remove the confirmation entirely because I know some people rely on it to avoid misclicks.

**Comment by emericv** [comment]
> Not at the moment, although the "shift+a" keyboard shortcut marks all entries as read, but does not ask for confirmation.
Yes, I have discovered this way too, but it's a bit less handy
> 
> I could add a user setting to enable/disable the confirmation (it will remove the possibility to mark entries older than x days though). I don't plan to remove the confirmation entirely because I know some people rely on it to avoid misclicks.
Yes, It's for this reason I suggest an optional setting to enable it.

**Comment by Athou** [comment]
I added a setting to disable the confirmation :)
