### ISSUE TITLE
Search time limit

### ISSUE THREAD

**Issue by rbedyakin** [Athou/commafeed#1122]
I'm always frustrated when commafeed does not return any search results in reasonable time. Please consider setting search query time limits.

**Comment by travelgirl-fics** [comment]
along the same lines, i would like to suggest that the feed/feed group search for new posts only a few times a day instead of on almost every selection.  while it can be nice to know every new post is available now, it takes quite a long time for busy feeds to return data and/or eliminate duplicates...  it is especially noticeable with feeds that normally update only once a day, and with groups that contain numerous feeds.

thanks...

**Comment by Athou** [comment]
Are those concerns still relevant, now that the [server upgrade](https://github.com/Athou/commafeed/discussions/1127) is done?

**Comment by travelgirl-fics** [comment]
it appears the lags are no longer happening.  thank you for fixing this so
quickly...

**Comment by rbedyakin** [comment]
Thank you! Now search results are returning much faster.
