### ISSUE TITLE
Some Feeds Result in 403

### ISSUE THREAD

**Issue by DennisJDufrene** [Athou/commafeed#1156]
**Describe the bug**
Some active RSS feeds result in a 403 error when attempting to subscribe.

**To Reproduce**
Add any of the following feeds and a 403 error occurs:

- https://www.sci.news/feed
- https://www.epa.gov/newsreleases/search/rss

The above are just examples. There have been several others.

**Expected behavior**
Active RSS Feeds should be subscribe-able.

**Screenshots**
The error provided is:

```
Error
org.apache.http.client.HttpResponseException: status code: 403, reason phrase: Server returned HTTP error code 403
```
**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): 3.10.0 (8ac452a)
- Browser: Firefox
- Device: Desktop

**Additional context**

**Comment by Athou** [comment]
What is the output of `curl -I https://www.sci.news/feed` on the server hosting your CommaFeed instance? Do you also get a 403?

**Comment by Athou** [comment]
Since it seems to work with curl and not with CommaFeed on the same server, my guess is that they are blocking CommaFeed requests based on the User Agent string.

You could try to change the user agent used by CommaFeed in the config.yml file to something like what [Chrome is sending](https://www.whatismybrowser.com/guides/the-latest-user-agent/chrome), it may solve your problem.

**Comment by rbedyakin** [comment]
Athou, could you fix this problem for https://www.commafeed.com/ ?
