### ISSUE TITLE
Duplicated Elements

### ISSUE THREAD

**Issue by Steve0Greatness** [Athou/commafeed#1174]
**Describe the bug**
I recently noticed that the [Tailscale Blog](https://tailscale.com/blog), when subscribed to with RSS, has duplicated elements (so it shows multiple version of the same post). This doesn't appear to be an issue with their feed itself, as seen on [their raw RSS feed](https://tailscale.com/blog/index.xml): each post only shows up one time.

**To Reproduce**

1. Go to CommaFeed.
2. Click on the Plus icon.
3. Subscribe to `https://tailscale.com/blog/index.xml`.
4. Click on the entry for Blog on Tailscale.
5. See how the posts are duplicated.

**Expected behavior**
There should only be one per post, not 2.

**Screenshots**
![Screenshot 2023-12-13 164503](https://github.com/Athou/commafeed/assets/75220768/d1bce5eb-a153-4b26-be99-a64a77952341)

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): commafeed.com
- Browser [e.g. chrome, firefox]: FireFox(desktop) & Kiwi(mobile)
- Device [e.g. desktop, mobile]: Desktop & Mobile

**Additional context**

N/A

**Comment by Athou** [comment]
Duplicate elements don't have the exact same URL, e.g. `https://tailscale.com/blog/travel-tips/` vs `https://tailscale.com/blog/travel-tips` (notice the trailing slash). I suspect the site changed the way they generate their RSS feed and since they use the article URL as the guid (e.g. `<guid>https://tailscale.com/blog/travel-tips</guid>`), CommaFeed treats those entries as separate entries. I think you need to contact the site owner if it continues to happen.
