### ISSUE TITLE
Mark all as read

### ISSUE THREAD

**Issue by Othman-92** [Athou/commafeed#1452]
hello
when i click on mark all as read the feed don't delete and they stay i can't delete them and they stay
thanks for your help

**Comment by Athou** [comment]
I'm sorry I don't understand what you mean. Could you please join a screenshot or something to explain a little further what the issue is?

**Comment by Othman-92** [comment]
thnaks for answer

my ''feeds'' are not deleted and remain even though I select ''mark all as read''.


https://github.com/Athou/commafeed/assets/112637497/ad998be6-93eb-4398-9f76-2ea5027fcf21

**Comment by Athou** [comment]
Oh, okay thanks for the video, I understand now.

I think it's because you have a lot of unread entries, it takes some time to mark everything as read. I just deployed a change for this that will mark entries faster, is it working now? A side effect of this is that entries should load significantly faster too.

**Comment by Othman-92** [comment]
yes now it work ,thank you veryb much for your good work
