### ISSUE TITLE
Option to ignore eTag header or use some other indicator?

### ISSUE THREAD

**Issue by kgunnar** [Athou/commafeed#1466]
**Is your feature request related to a problem? Please describe.**
I'm trying to migrate/consolidate all my RSS feeds from various clients to CommaFeed, however a number servers do not appear to be updating the etag header on the responses as the feeds are not updating and the "Last refresh message" always says "eTagHeader is the same". It does appear that the server is keeping the etag the same for some reason but the XML lastBuildDate does update with the new articles.

**Describe the solution you'd like**
Perhaps an option to ignore etag or look at alternative options (such as the channel lastBuildDate in the RSS XML) instead of etag would prevent this?

**Describe alternatives you've considered**
I'm unsure of alternatives as I do not have control over the servers and I'm not getting any response from the owners. I could put a proxy in between to strip the header but this seems relatively hacky and complicated versus just being able to ignore it in CommaFeed.

**Additional context**
I still have these feeds on a TheOldReader account and they work perfectly fine. I surmise that TheOldReader must not check the e-tag or is doing something else to know that the feed is actually updating even though the etag isn't changing.

**Comment by Athou** [comment]
This is tricky because CommaFeed is at its core multi-user. A feed is only fetched once for all users that are subscribed to that feed, so a setting like that could not be set by a user, because it will have an impact on other users. A setting could be added at the instance level but it's not a good idea to ignore the eTag headers for all feeds because one of them is misconfigured. This is the same reason why https://github.com/Athou/commafeed/issues/1162 is not yet supported.

I understand that you do not get any response from the owners of the feed but fixing the feed itself would be the cleanest solution.

**Comment by kgunnar** [comment]
I agree that the server operating correctly would be the most ideal solution. I can see you may intend to optimize fetching the feeds only once although that seems like it may cause more trouble than it is worth as it opens up a lot of issues such the one you mentioned, not being able to do authentication by user. I would imagine most all self-hosted instances are only a single user anyway and even if there are multiple users on larger instances, the likelihood of multiple users using the same feeds and saving a call or two is probably somewhat low versus being much more flexible in supporting per-user feed options.

That said, this particular issue wouldn't even need to be a per-user setting as this problem would affect all users equally. I was quite impressed with this project overall but unfortunately I'll now have to decide whether I want to write something to sit in the middle and strip the header off requests or just switch to a different reader that can handle these types of issues.
