### ISSUE TITLE
YouTube RSS video feeds show videos from years ago

### ISSUE THREAD

**Issue by Jiehong** [Athou/commafeed#1486]
**Describe the bug**

Since the new web ui version of commafeed, old YouTube videos appear in the feed, even they are from many years ago.

for example, today I got the following video in my feed:

https://www.youtube.com/watch?v=c5dGlgdHlaY

Because I’m following the rss feed of https://www.youtube.com/@ThisOldTony/videos.

in commafeed.com, the feed url in this example is https://www.youtube.com/feeds/videos.xml?channel_id=UC5NO8MgTQKHAWXp6z8Xl7yQ

**Environment (please complete the following information):**

- CommaFeed version (or "commafeed.com"): commafeed.com
- Browser [e.g. chrome, firefox]: any 
- Device [e.g. desktop, mobile]: any

**Additional context**

this used to work just fine.
This happens for so many YouTube feeds now. The date displayed in commafeed.com seems wrong: when clicking the video and going to YouTube, it shows xx years ago (I’ve had between 1 and 12 years ago)

**Comment by Athou** [comment]
I think you're right. Since January there's a new setting `maxEntriesAgeDays` that deletes entries older than a year from the database to keep the size of the database in check.

I think what's happening is:
- The video was detected by CommaFeed when it was published
- When the video was a year old, it was deleted from the database
- Someone recently edited the description of the video:
![image](https://github.com/user-attachments/assets/07200e30-6aa5-4447-97b9-2ac9d12398bd)
- CommaFeed incorrectly reads the `updated` instead of the `published` field and considers it's a new video

I will try to fix this ASAP.

**Comment by Athou** [comment]
I just deployed a fix on commafeed.com that should fix this. Let me know here if it happens again!

**Comment by Jiehong** [comment]
@Athou thanks a lot for such a quick and efficient response!

I’ll monitor it.

You’re outstanding :)
