### ISSUE TITLE
Set Refresh Interval for Feeds

### ISSUE THREAD

**Issue by AsixJin** [Athou/commafeed#1509]
**Is your feature request related to a problem? Please describe.**
Each feed's refresh interval is 5 minutes, which I think it's a bit much. I don't want to get rate limited from a few of my feeds because of the numerous refreshes.

**Describe the solution you'd like**
It would be nice to set a refresh interval for each feed.

**Comment by Athou** [comment]
This is tricky because CommaFeed is at its core multi-user. A feed is only fetched once for all users that are subscribed to that feed, so a setting like that could not be set by a user, because it will have an impact on other users. 

Since 5.0.0, there is however the new [commafeed.feed-refresh.interval-empirical](https://github.com/Athou/commafeed/blob/master/commafeed-server/doc/commafeed.adoc#commafeed_commafeed-feed-refresh-interval-empirical) setting that will make the feed engine refresh feeds at intervals based on the feed's activity.

**Comment by Athou** [comment]
> How do I use/change the setting?

See the [Configuration section of the README](https://github.com/Athou/commafeed/tree/master?tab=readme-ov-file#configuration)
