### ISSUE TITLE
CommaFeed can't load items from https://www.ilrisparmiotradito.it/rss.xml

### ISSUE THREAD

**Issue by paolo6671** [Athou/commafeed#1629]
Steps to reproduce:
- in CommaFeed add feed https://www.ilrisparmiotradito.it/rss.xml
- the analysis step is ok, but in the end no item is loaded.
Thank you

**Comment by Athou** [comment]
I assume you use commafeed.com

All entries are there but they are marked as read because they are older than a month. See [this](https://github.com/Athou/commafeed/discussions/1567) for an explanation.

**Comment by paolo6671** [comment]
Thank you for your explanation. There should be one entry published on 25/11/2024 (see attach).
![image](https://github.com/user-attachments/assets/f8a00a46-bfee-42fe-b6a7-b9b635c4fec8)

**Comment by Athou** [comment]
CommaFeed currently only adds entries if they have either a guid or a link as those are used to uniquely identify an entry and avoid inserting multiple times the same entry.

 Entries in that feed have neither. 
![image](https://github.com/user-attachments/assets/cba5c4e6-b009-4ca7-880f-ecec227f9849)

I guess this is a recent change because there are entries for that feed up to 4 months ago. Could you contact the website owners to ask them to put back at least the link element in the feed?

**Comment by paolo6671** [comment]
I'll try to contact the webmaster. Thanks!

**Comment by Athou** [comment]
Looks like the feed has been fixed, I'm gonna close this issue 👍 

![image](https://github.com/user-attachments/assets/c30e0e6a-8895-49fa-9109-1b9d54922efd)
![image](https://github.com/user-attachments/assets/6a0b78a6-fc14-4843-8ace-0121bd9d6c70)
