### ISSUE TITLE
Problem with Chinese content encoding

### ISSUE THREAD

**Issue by erobotics** [Athou/commafeed#480]
tried to read http://www.mitbbs.com/rss/top.xml

both on my own server and commafeed.com I could not get the expected result. 

Something like:
wp8����Ļ������app��ʲô

Or:
???????????????????????????????? ??????????????????????????
![screenshot from 2013-08-06 11 18 04](https://f.cloud.github.com/assets/5175100/917897/7b9875c4-feab-11e2-8d65-00d543a2574e.png)
![screenshot from 2013-08-06 11 18 23](https://f.cloud.github.com/assets/5175100/917898/7ba1e3fc-feab-11e2-8a8c-a025f5228d7e.png)

**Comment by mozzenior** [comment]
I was having the same issue and discovered the root cause is my misconfiguration of MySQL.

MySQL on Debian 8 by default doesn't support UTF-8, hence CJK characters become "???". Refer this [StackOverflow post](http://stackoverflow.com/questions/3513773/change-mysql-default-character-set-to-utf-8-in-my-cnf) to enable UTF-8 for MySQL.

Note: Feed entries already fetched will not be automatically converted to UTF-8 after re-configuring MySQL. But I think this is not a big deal.
