### ISSUE TITLE
Mark as read does not seem to work

### ISSUE THREAD

**Issue by christoph88** [Athou/commafeed#600]
Hi, the mark as read function does not seem to work. I get a progress bar but nothing happens. (christoph88)

**Comment by barbuslex** [comment]
Hi,

Same problem for me. Is it impossible to mark all feed as read.
My account: Barbuslex

Thanks to solve it ;)

**Comment by dsferruzza** [comment]
Hi!

It happens quite often to me too :/
It seems that some insertions in DB (caused by new entries *or* by marking an entry as read) fail because the new record has an ID that is already taken.
It also seems that hibernate doesn't use PostgreSQL `sequences` to determine the next ID to use (but I could be wrong), so I don't really understand how hibernate does that... (I don't know hibernate well)

If I restart CommaFeed several times, it works, eventually.
So I don't really understand what's going on, but this doesn't seem too much deterministic :/

**Comment by dsferruzza** [comment]
Hi!

Any update on this?

I'm using the last version from master (4a056a0d27a5952512c6aa87209b9b3ab6875827).
It worked without problems for a while but now the duplicated key errors are back.

Every time I restart commafeed, it takes `the last (failing) id + 1000` and tries to insert in `feedentrycontents` with this new id, which fails.
So I restart it again, it picks a new id, and so on...

Maybe it should be a good idea to consider using random UUIDs as primary keys, to avoid that kind of problems? (see https://www.clever-cloud.com/blog/engineering/2015/05/20/why-auto-increment-is-a-terrible-idea/)

(But if you have other ideas to fix this problem, I'm very interested!)
