### ISSUE TITLE
Navigation icons replaced by squares

### ISSUE THREAD

**Issue by ScuttleSE** [Athou/commafeed#734]
I just did a git pull, and all the UI-icons are replaced by squares. Did I mess something up?

http://i.imgur.com/aWYZxRR.png

**Comment by dsferruzza** [comment]
Same here!

I get an error in Firefox's web console: `GET 
https://mydomain/css/css/font/fontawesome-webfont.woff [HTTP/1.1 404 Not Found 34ms]`

**Comment by RavenB** [comment]
Just to confirm, same problem here using latest git clone.

**Comment by Athou** [comment]
Thanks for the heads up !
see https://github.com/jonathanepollack/gulp-minify-css/issues/95 for the reason.

**Comment by shinnn** [comment]
@ScuttleSE @dsferruzza @RavenB @Athou 

The path problem was fixed in gulp-minify-css v1.1.4 so this workaround https://github.com/RavenB/commafeed/commit/4a52bd0cb736d8a41a7fa4a1c3f26a801e14c6f0 is not needed any more. Please update the plugin to the latest version.

Thanks for using gulp-minify-css!

**Comment by Athou** [comment]
Awesome, thank you!

**Comment by shinnn** [comment]
Unfortunately I confirmed gulp-minify-css v1.1.4 is broken too, and released v1.1.5 just now.

**Comment by RavenB** [comment]
@Athou @shinnn Just made fresh build, confirmed works great. All icons back to normal.
