### ISSUE TITLE
Is it possible to mark as read when scrolling down and displaying titles only?

### ISSUE THREAD

**Issue by Yakito** [Athou/commafeed#773]
Hello,
Can someone point me in the direction to which file should be edited to be able to have the same functionality of the expanded view (marking as read while scrolling) but while displaying titles only?

Any tip will be appreciated!
Thanks!

**Comment by lutzhorn** [comment]
Why should reading the titles only classify an entry as "read"?

**Comment by Yakito** [comment]
Sometimes you read the title and you know it is not important so you want
to discard it or mark it as read. The news+ app for Android provides this
functionality where it shows a small preview of the article and when you
scroll down if you haven't opened it it is considered read.

**Comment by Bystroushaak** [comment]
I would also use this very much.

I have a lot of high-frequency subscriptions, which generate hundreds or thousands of submissions per week, and they don't provide content. Reddit is good example of this, you can only read title of the post, not the content itself.

When I am skimming over the posted items, I only mark some of them (for /r/programming, it is like every hundredth or so) as stared and all the rest as read. I can't use this workflow right now, and I would really like to do so, because mark all as read feature is really uncomfortable, because it forces you to read all 2000 posts at once, or you loose progress.

**Comment by Bystroushaak** [comment]
For example:

![commafeed](https://user-images.githubusercontent.com/227282/53508787-bc5c3b80-3aba-11e9-950a-a070ea51fc48.png)

It is really unpleasant to read ~thousand of posts in session, when only thing you do is to categorize whether it is interesting for you or not.

**Comment by Athou** [comment]
What about the button "Mark all as read up to here" at the bottom of each entry? Would that solve the issue for you?
![image](https://user-images.githubusercontent.com/1256795/53510772-14953c80-3abf-11e9-803c-c59b142fd3f4.png)

**Comment by Bystroushaak** [comment]
Okay, that does solve my problems, thanks. Maybe it would be better to somehow highlight it (add some text next to it?), because I didn't noticed it until you mentioned it.

**Comment by shmightworks** [comment]
I would want this as well.
