### ISSUE TITLE
media:group

### ISSUE THREAD

**Issue by RadAd** [Athou/commafeed#800]
Commafeed doesn't seem to show any of the media:group section as described in http://www.rssboard.org/media-rss.

Is there any way to get it to display it?

An example rss feed: https://www.youtube.com/feeds/videos.xml?channel_id=UCy1Ms_5qBTawC-k7PVjHXKQ

**Comment by azmeuk** [comment]
For the record, here is how a [youtube feed](https://www.youtube.com/feeds/videos.xml?channel_id=UC7_gcs09iThXybpVgjHZ_7g) is displayed:
![commafeed-youtube](https://user-images.githubusercontent.com/60163/69148306-49757380-0ad4-11ea-8c06-9da32fd1f14a.png)

when these tags are available: 

```xml
  <media:group>
   <media:title>Can You Observe a Typical Universe?</media:title>
   <media:content url="https://www.youtube.com/v/q-6oU3jXAho?version=3" type="application/x-shockwave-flash" width="640" height="390"/>
   <media:thumbnail url="https://i2.ytimg.com/vi/q-6oU3jXAho/hqdefault.jpg" width="480" height="360"/>
   <media:description>Sign Up on Patreon to get access to the Space Time Discord! 
https://www.patreon.com/pbsspacetime

Check out the Space Time Merch Store
https://pbsspacetime.com/

The moment you started observing reality, you hopelessly polluted any conclusions you might make about it. The anthropic principle guarantees that you are NOT seeing the universe in most typical state. But used correctly, this highly controversial idea can be extremely powerful. So, how do you correctly use the anthropic principle?

Hosted by Matt O'Dowd
Written by Matt O'Dowd
Graphics by Leonardo Scholzer &amp; Adriano Leal
Directed by: Andrew Kornhaber
Executive Producers: Eric Brown &amp; Andrew Kornhaber 

Special Thanks to Dr. Flournoy!!! Check out his lectures Below:
Particle Physics: https://www.youtube.com/playlist?list=PLDlWMHnDwylijo0yfs3xUN9ad6-YZjPLT
General Relativity: https://www.youtube.com/playlist?list=PLDlWMHnDwyliMevB36wgRbjXhJkoN_RUQ

...</media:description>
   <media:community>
    <media:starRating count="7174" average="4.92" min="1" max="5"/>
    <media:statistics views="164545"/>
   </media:community>
  </media:group>
```

**Comment by azmeuk** [comment]
Please stale bot, let it live.

**Comment by Athou** [comment]
What content would you expect?

Should CommaFeed use the `media:thumbnail` and `media:description` tags? Only if the content of the entry is empty?

**Comment by azmeuk** [comment]
Yes, I would expect both to be displayed, even if there is a content in the entry.

**Comment by Athou** [comment]
I read the spec at https://www.rssboard.org/media-rss and it's rather complex, basically all elements are optional. The main element seems to be `media:content` but it's also optional.

Feeds mentioned in https://github.com/Athou/commafeed/issues/893 https://github.com/Athou/commafeed/issues/820 https://github.com/Athou/commafeed/issues/867 and https://github.com/Athou/commafeed/issues/716 all behave differently.

Some use `media:content`, some don't. Some use `media:thumbnail`, some don't. Youtube feeds are even stranger since they use a content type `application/x-shockwave-flash` which is now unsupported by all browsers and would require a specific handling to translate to an iframe pointing to the embedded version of the video (or something like that).

All in all, supporting the `media`  extension looks like a lot of effort right now :(

**Comment by azmeuk** [comment]
I think the most common usage is videos sharing, and as you pointed `media:thumbnail` and `media:description` support would be just good enough so we can use commafeed instead of youtube/peertube subscriptions.

**Comment by Athou** [comment]
Actually that seems to be a nice compromise. I'll see what I can do.

**Comment by Athou** [comment]
I added support for `media:thumbnail` and `media:description`, but they will be displayed only if the main content is empty, because some feeds (like https://www.reddit.com/r/HighQualityGifs/.rss mentioned in https://github.com/Athou/commafeed/issues/867) have the image both in the content and as a media extension, resulting in the image displayed twice.

If anyone has a better idea let me know :)
