### ISSUE TITLE
Cannot delete account or change password

### ISSUE THREAD

**Issue by fturco** [Athou/commafeed#805]
I have an account on the [commafeed.com](http://commafeed.com/) website. I'd like to either set a stronger password and forget about my account or delete it entirely, but I can't do that. Commafeed.com fails to accept my new password and after requesting account removal it still lets me in with the old password.

**Comment by dcelasun** [comment]
I'm using a self hosted version of Commafeed (using a MySQL backend) and I can't change my password either. Any ideas @Athou?

**Comment by glujan** [comment]
This bug is still present on www.commafeed.com.

**Comment by Primokorn** [comment]
I also have the same issue. Nothing changes when I press the 'Save' button.

**Comment by Athou** [comment]
commafeed.com has been updated to the latest commit on master.

**Comment by glujan** [comment]
I still can log in to the account which should be deleted. Changing a password works correctly.

**Comment by Athou** [comment]
The new version fixes the delete button, did you try to delete your account again?

**Comment by glujan** [comment]
@Athou Yes, I did. I've just tried doing it again and it is not working - I still can log in to the account.

**Comment by glujan** [comment]
Here are two more details which may be handy for you:
* After confirming the account deletion, my session ends and I'm redirected to the main website (`/#/welcome`).
* After I log in to the should-be-deleted account I still can see all my feeds and categories.

Let me know if you need more information or any other kind of help from my side.

The same behaviour is reported in #817 so we can move there, otherwise please reopen this issue as it is not resolved yet.
