### ISSUE TITLE
Expanded view not loading fully

### ISSUE THREAD

**Issue by karhima** [Athou/commafeed#962]
Rock Paper Shotgun updated their website a while ago and since then, the expanded view for that feed isn't working properly. When clicking on the title, the expanded view only shows the title and a view words of the first sentence, no picture or short description.
This is the URL: http://feeds.feedburner.com/RockPaperShotgun
I'm on Firefox 86.0.1, I tried to delete cache, unsubscribe/subscribe to the feed, but that didn't fix it.
Is there anything else I could try?

**Comment by Athou** [comment]
There are two `description` tags for each item in their feed, which is not correct.

![image](https://user-images.githubusercontent.com/1256795/111074582-dfac8480-84e3-11eb-932a-2dcf2f80a6ad.png)

The feed is not valid because of this according to https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.rockpapershotgun.com%2Ffeed
`item contains more than one description (98 occurrences)`

Maybe you could contact them?

**Comment by karhima** [comment]
Thank you for the quick response, I'll try!
