### ISSUE TITLE
End to end encryption

### ISSUE THREAD

**Issue by trymeouteh** [Athou/commafeed#996]
Adding E2EE were all of your RSS feeds and subscriptions are encrypted and the server cannot see your feed or subscriptions. And having the connection between the browser or RSS client to the server encrypted.

There are no private open source RSS feeds out there. There are encrypted email providers such as ProtonMail, Tutanota and CTemplar, there are encrypted calendar and contacts syncing services like EteSync, and there are encrypted cloud storage services such as Sync.com and Filen. Why not an encrypted RSS feed for privacy?

**Comment by Athou** [comment]
How would CommaFeed be able to fetch feeds continuously in the background so that when you're visiting CommaFeed all your feed subscriptions are up to date, if everything is encrypted?

Also, feeds are publicly available information so there's little point really in trying to encrypt their url and content.

If you're concerned about privacy, hosting a CommaFeed instance yourself is always an option.
